# The contents of this file is based on https://github.com/home-assistant/core/blob/dev/pyproject.toml

target-version = "py312"

[lint]
select = [
    "ALL",
]
ignore = [
    "ANN401", # Dynamically typed expressions (typing.Any) are disallowed
    "D203", # no-blank-line-before-class (incompatible with formatter)
    "D212", # multi-line-summary-first-line (incompatible with formatter)
    "COM812", # incompatible with formatter
    "ISC001", # incompatible with formatter
    "FIX002", # TODO provide context for future work
    "PLR2044", # Line with empty comment
]

[lint.flake8-pytest-style]
fixture-parentheses = false

[lint.pyupgrade]
keep-runtime-typing = true

[lint.mccabe]
max-complexity = 25

[lint.per-file-ignores]
"**/tests/**.py" = [
    "ANN001", # missing-type-function-argument
    "ANN201", # missing-return-type-undocumented-public-function
    "ARG001", # unused-function-argument
    "PLR2004", # magic-value-comparison
    "S101", # assert
    "S311", # suspicious-non-cryptographic-random-usage
    "SLF001", # private-member-access
    "S105", # hardcoded-password-string
    "S106", # hardcoded-password-func-arg
    "S107", # hardcoded-password-default
]
